services:
  spark:
    build: .
    command: >
      spark-submit 
      --master local[*] 
      --driver-memory 1g 
      --executor-memory 1g 
      /app/src/spark_practice/my_code.py
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app/src